#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar  3 12:00:17 2020

@author: aram
"""

WV_FILE_PATH = "../data/Word2vec_from_Google/model.wv"
GOOGLE_WORD2VEC_MODEL_FILE_PATH = "../data/Word2vec_from_Google/GoogleNews-vectors-negative300.bin"
#BIDAF_MODEL_FILE_PATH = "../data/bidaf-elmo-model-2020.03.19.tar.gz"
BIDAF_MODEL_FILE_PATH = "../data/bidaf-model-2017.09.15-charpad.tar.gz"

REVIEWS_FROM_YELP_FILE_PATH = '../data/Free_data_from_Yelp/reviews.json'
TIPS_FROM_YELP_FILE_PATH = '../data/Free_data_from_Yelp/tips.json'

TIPS_SPLIT_INTO_SENTENCES_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_OR_TOO_LONG_FILE_PATH = "../data/Free_data_from_Yelp_preprocessed/tips_split_into_sentences_with_rows_removed_if_text_length_too_short_or_too_long.json"
REVIEWS_SPLIT_INTO_SENTENCES_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_OR_TOO_LONG_FILE_PATH = "../data/Free_data_from_Yelp_preprocessed/reviews_split_into_sentences_with_rows_removed_if_text_length_too_short_or_too_long.json"
TIPS_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_FILE_PATH = "../data/Free_data_from_Yelp_preprocessed/tips_with_rows_removed_if_text_length_too_short.json"
REVIEWS_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_FILE_PATH = "../data/Free_data_from_Yelp_preprocessed/reviews_with_rows_removed_if_text_length_too_short.json"


QUESTIONS_WITH_ANSWERS_FROM_YELP_FILE_PATH = "../data/answers_only_from_first_question_pages.csv"

ANSWERS_FROM_TIPS_WITH_WV_FILE_PATH = '../data/Answers/Answers_from_tips_with_wv.csv'
ANSWERS_FROM_REVIEWS_WITH_WV_FILE_PATH = '../data/Answers/Answers_from_reviews_with_wv.csv'
ANSWERS_FROM_TIPS_WITH_WV_AND_BIDAF_FILE_PATH = "../data/Answers/Answers_from_tips_with_wv_and_bidaf.csv"
ANSWERS_FROM_REVIEWS_WITH_WV_AND_BIDAF_FILE_PATH = "../data/Answers/Answers_from_reviews_with_wv_and_bidaf.csv"
ANSWERS_FROM_TIPS_WITH_WV_AND_BERT_FILE_PATH = "../data/Answers/Answers_from_tips_with_wv_and_bert.csv"
ANSWERS_FROM_REVIEWS_WITH_WV_AND_BERT_FILE_PATH = "../data/Answers/Answers_from_reviews_with_wv_and_bert.csv"
ANSWERS_FROM_TIPS_WITH_WV_AND_BIDAF_WITHOUT_REARRANGING_AFTER_BIDAF_FILE_PATH = "../data/Answers/Answers_from_tips_with_wv_and_bidaf_without_rearranging_after_bidaf.csv"
ANSWERS_FROM_REVIEWS_WITH_WV_AND_BIDAF_WITHOUT_REARRANGING_AFTER_BIDAF_FILE_PATH = "../data/Answers/Answers_from_reviews_with_wv_and_bidaf_without_rearranging_after_bidaf.csv"
ANSWERS_FROM_TIPS_WITH_WV_AND_BERT_WITHOUT_REARRANGING_AFTER_BERT_FILE_PATH = "../data/Answers/Answers_from_tips_with_wv_and_bert_without_rearranging_after_bert.csv"
ANSWERS_FROM_REVIEWS_WITH_WV_AND_BERT_WITHOUT_REARRANGING_AFTER_BERT_FILE_PATH = "../data/Answers/Answers_from_reviews_with_wv_and_bert_without_rearranging_after_bert.csv"



ANSWERS_FROM_TIPS_WITH_TF_IDF_FILE_PATH = '../data/Answers/Answers_from_tips_with_tf_idf.csv'
ANSWERS_FROM_REVIEWS_WITH_TF_IDF_FILE_PATH = '../data/Answers/Answers_from_reviews_with_tf_idf.csv'
ANSWERS_FROM_TIPS_WITH_TF_IDF_AND_BIDAF_FILE_PATH = '../data/Answers/Answers_from_tips_with_tf_idf_and_bidaf.csv'
ANSWERS_FROM_REVIEWS_WITH_TF_IDF_AND_BIDAF_FILE_PATH = '../data/Answers/Answers_from_reviews_with_tf_idf_and_bidaf.csv'
ANSWERS_FROM_TIPS_WITH_TF_IDF_AND_BERT_FILE_PATH = '../data/Answers/Answers_from_tips_with_tf_idf_and_bert.csv'
ANSWERS_FROM_REVIEWS_WITH_TF_IDF_AND_BERT_FILE_PATH = '../data/Answers/Answers_from_reviews_with_tf_idf_and_bert.csv'


ANSWERS_FROM_TIPS_WITH_IWCS_FILE_PATH = '../data/Answers/Answers_from_tips_with_iwcs.csv'
ANSWERS_FROM_REVIEWS_WITH_IWCS_FILE_PATH = '../data/Answers/Answers_from_reviews_with_iwcs.csv'
ANSWERS_FROM_TIPS_WITH_IWCS_AND_BIDAF_FILE_PATH = '../data/Answers/Answers_from_tips_with_iwcs_and_bidaf.csv'
ANSWERS_FROM_REVIEWS_WITH_IWCS_AND_BIDAF_FILE_PATH = '../data/Answers/Answers_from_reviews_with_iwcs_and_bidaf.csv'
ANSWERS_FROM_TIPS_WITH_IWCS_AND_BERT_FILE_PATH = '../data/Answers/Answers_from_tips_with_iwcs_and_bert.csv'
ANSWERS_FROM_REVIEWS_WITH_IWCS_AND_BERT_FILE_PATH = '../data/Answers/Answers_from_reviews_with_iwcs_and_bert.csv'
ANSWERS_FROM_TIPS_WITH_IWCS_AND_BIDAF_WITHOUT_REARRANGING_AFTER_BIDAF_FILE_PATH = '../data/Answers/Answers_from_tips_with_iwcs_and_bidaf_without_rearranging_after_bidaf.csv'
ANSWERS_FROM_REVIEWS_WITH_IWCS_AND_BIDAF_WITHOUT_REARRANGING_AFTER_BIDAF_FILE_PATH = '../data/Answers/Answers_from_reviews_with_iwcs_and_bidaf_without_rearranging_after_bidaf.csv'
ANSWERS_FROM_TIPS_WITH_IWCS_AND_BERT_WITHOUT_REARRANGING_AFTER_BERT_FILE_PATH = '../data/Answers/Answers_from_tips_with_iwcs_and_bert_without_rearranging_after_bert.csv'
ANSWERS_FROM_REVIEWS_WITH_IWCS_AND_BERT_WITHOUT_REARRANGING_AFTER_BERT_FILE_PATH = '../data/Answers/Answers_from_reviews_with_iwcs_and_bert_without_rearranging_after_bert.csv'



"""
ANSWERS_FROM_TIPS_WITH_WV_AND_BIDAF_WITH_LENGTH_BOUNDARY_FILE_PATH = '../data/Answers/Answers_from_tips_with_wv_and_bidaf_with_length_boundary.csv'
ANSWERS_FROM_REVIEWS_WITH_WV_AND_BIDAF_WITH_LENGTH_BOUNDARY_FILE_PATH = '../data/Answers/Answers_from_reviews_with_wv_and_bidaf_with_length_boundary.csv'
ANSWERS_FROM_TIPS_WITH_IWCS_AND_BIDAF_WITH_LENGTH_BOUNDARY_FILE_PATH = '../data/Answers/Answers_from_tips_with_iwcs_and_bidaf_with_length_boundary.csv'
ANSWERS_FROM_REVIEWS_WITH_IWCS_AND_BIDAF_WITH_LENGTH_BOUNDARY_FILE_PATH = '../data/Answers/Answers_from_reviews_with_iwcs_and_bidaf_with_length_boundary.csv'
ANSWERS_FROM_TIPS_WITH_TF_IDF_AND_BIDAF_WITH_LENGTH_BOUNDARY_FILE_PATH = '../data/Answers/Answers_from_tips_with_tf_idf_and_bidaf_with_length_boundary.csv'
ANSWERS_FROM_REVIEWS_WITH_TF_IDF_AND_BIDAF_WITH_LENGTH_BOUNDARY_FILE_PATH = '../data/Answers/Answers_from_reviews_with_tf_idf_and_bidaf_with_length_boundary.csv'
"""

TF_IDF_RAM_FRIENDLY_MODEL_FOR_TIPS_SPLIT_INTO_SENTENCES_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_OR_TOO_LONG_DIR_PATH = "../data/TF-IDF_models/RAM_friendly/RAM_friendly_for_tips_split_into_sentences_with_rows_removed_if_text_length_too_short_or_too_long/"
TF_IDF_RAM_FRIENDLY_MODEL_FOR_REVIEWS_SPLIT_INTO_SENTENCES_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_OR_TOO_LONG_DIR_PATH = "../data/TF-IDF_models/RAM_friendly/RAM_friendly_for_reviews_split_into_sentences_with_rows_removed_if_text_length_too_short_or_too_long/"
TF_IDF_RAM_FRIENDLY_MODEL_FOR_TIPS_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_DIR_PATH = "../data/TF-IDF_models/RAM_friendly/RAM_friendly_for_tips_with_rows_removed_if_text_length_too_short/"
TF_IDF_RAM_FRIENDLY_MODEL_FOR_REVIEWS_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_DIR_PATH = "../data/TF-IDF_models/RAM_friendly/RAM_friendly_for_reviews_with_rows_removed_if_text_length_too_short/"

DF_RAM_FRIENDLY_MODEL_FOR_TIPS_SPLIT_INTO_SENTENCES_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_OR_TOO_LONG_DIR_PATH = "../data/DF_models/RAM_friendly/RAM_friendly_for_tips_split_into_sentences_with_rows_removed_if_text_length_too_short_or_too_long/"
DF_RAM_FRIENDLY_MODEL_FOR_REVIEWS_SPLIT_INTO_SENTENCES_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_OR_TOO_LONG_DIR_PATH = "../data/DF_models/RAM_friendly/RAM_friendly_for_reviews_split_into_sentences_with_rows_removed_if_text_length_too_short_or_too_long/"
DF_RAM_FRIENDLY_MODEL_FOR_TIPS_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_DIR_PATH = "../data/DF_models/RAM_friendly/RAM_friendly_for_tips_with_rows_removed_if_text_length_too_short/"
DF_RAM_FRIENDLY_MODEL_FOR_REVIEWS_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_DIR_PATH = "../data/DF_models/RAM_friendly/RAM_friendly_for_reviews_with_rows_removed_if_text_length_too_short/"

"""
FILE_PATH_FOR_TIPS_SPLIT_INTO_SENTENCES_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_OR_TOO_LONG_WITH_CENTROIDS_WITHOUT_PREPROCESSING = "../data/Centroids/tips_split_into_sentences_with_rows_removed_if_text_length_too_short_or_too_long_with_centroids_without_preprocessing.csv"
FILE_PATH_FOR_REVIEWS_SPLIT_INTO_SENTENCES_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_OR_TOO_LONG_WITH_CENTROIDS_WITHOUT_PREPROCESSING = "../data/Centroids/reviews_split_into_sentences_with_rows_removed_if_text_length_too_short_or_too_long_with_centroids_without_preprocessing.csv"
FILE_PATH_FOR_TIPS_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_WITH_CENTROIDS_WITHOUT_PREPROCESSING = "../data/Centroids/tips_with_rows_removed_if_text_length_too_short_with_centroids_without_preprocessing.csv"
FILE_PATH_FOR_REVIEWS_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_WITH_CENTROIDS_WITHOUT_PREPROCESSING = "../data/Centroids/reviews_with_rows_removed_if_text_length_too_short_with_centroids_without_preprocessing.csv"
"""

FILE_PATH_FOR_TIPS_SPLIT_INTO_SENTENCES_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_OR_TOO_LONG_WITH_CENTROIDS_WITH_PREPROCESSING = "../data/Centroids/tips_split_into_sentences_with_rows_removed_if_text_length_too_short_or_too_long_with_centroids_with_preprocessing.csv"
FILE_PATH_FOR_REVIEWS_SPLIT_INTO_SENTENCES_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_OR_TOO_LONG_WITH_CENTROIDS_WITH_PREPROCESSING = "../data/Centroids/reviews_split_into_sentences_with_rows_removed_if_text_length_too_short_or_too_long_with_centroids_with_preprocessing.csv"
FILE_PATH_FOR_TIPS_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_WITH_CENTROIDS_WITH_PREPROCESSING = "../data/Centroids/tips_with_rows_removed_if_text_length_too_short_with_centroids_with_preprocessing.csv"
FILE_PATH_FOR_REVIEWS_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_WITH_CENTROIDS_WITH_PREPROCESSING = "../data/Centroids/reviews_with_rows_removed_if_text_length_too_short_with_centroids_with_preprocessing.csv"

FILE_PATH_FOR_TIPS_SPLIT_INTO_SENTENCES_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_OR_TOO_LONG_WITH_IWCS = "../data/IWCS/tips_split_into_sentences_with_rows_removed_if_text_length_too_short_or_too_long_with_iwcs.csv"
FILE_PATH_FOR_REVIEWS_SPLIT_INTO_SENTENCES_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_OR_TOO_LONG_WITH_IWCS = "../data/IWCS/reviews_split_into_sentences_with_rows_removed_if_text_length_too_short_or_too_long_with_iwcs.csv"
FILE_PATH_FOR_TIPS_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_WITH_IWCS = "../data/IWCS/tips_with_rows_removed_if_text_length_too_short_with_iwcs.csv"
FILE_PATH_FOR_REVIEWS_WITH_ROWS_REMOVED_IF_TEXT_LENGTH_TOO_SHORT_WITH_IWCS = "../data/IWCS/reviews_with_rows_removed_if_text_length_too_short_with_iwcs.csv"

#FILE_PATH_FOR_TIPS_WITH_IWCS_WITHOUT_PREPROCESSING = "../data/IWCS/tips_with_iwcs_without_preprocessing.csv"
#FILE_PATH_FOR_REVIEWS_WITH_IWCS_WITHOUT_PREPROCESSING = "../data/IWCS/reviews_with_iwcs_without_preprocessing.csv"
#FILE_PATH_FOR_TIPS_WITH_IWCS_WITH_PREPROCESSING = "../data/IWCS/tips_with_iwcs_with_preprocessing.csv"
#FILE_PATH_FOR_REVIEWS_WITH_IWCS_WITH_PREPROCESSING = "../data/IWCS/reviews_with_iwcs_with_preprocessing.csv"

CENTROID_SIMILARITIES_OF_ANSWERS_FROM_REVIEWS_WITH_IWCS_FILE_PATH = "../data/Analysis_of_answers/centroid_similarities_of_answers_from_reviews_with_iwcs.csv"
CENTROID_SIMILARITIES_OF_ANSWERS_FROM_REVIEWS_WITH_IWCS_AND_BIDAF_FILE_PATH = "../data/Analysis_of_answers/centroid_similarities_of_answers_from_reviews_with_iwcs_and_bidaf.csv"
CENTROID_SIMILARITIES_OF_ANSWERS_FROM_REVIEWS_WITH_IWCS_AND_BIDAF_WITH_LENGTH_BOUNDARY_FILE_PATH = "../data/Analysis_of_answers/centroid_similarities_of_answers_from_reviews_with_iwcs_and_bidaf_with_length_boundary.csv"
CENTROID_SIMILARITIES_OF_ANSWERS_FROM_REVIEWS_WITH_TF_IDF_FILE_PATH = "../data/Analysis_of_answers/centroid_similarities_of_answers_from_reviews_with_tf_idf.csv"
CENTROID_SIMILARITIES_OF_ANSWERS_FROM_REVIEWS_WITH_TF_IDF_AND_BIDAF_FILE_PATH = "../data/Analysis_of_answers/centroid_similarities_of_answers_from_reviews_with_tf_idf_and_bidaf.csv"
CENTROID_SIMILARITIES_OF_ANSWERS_FROM_REVIEWS_WITH_TF_IDF_AND_BIDAF_WITH_LENGTH_BOUNDARY_FILE_PATH = "../data/Analysis_of_answers/centroid_similarities_of_answers_from_reviews_with_tf_idf_and_bidaf_with_length_boundary.csv"
CENTROID_SIMILARITIES_OF_ANSWERS_FROM_TIPS_WITH_IWCS_FILE_PATH = "../data/Analysis_of_answers/centroid_similarities_of_answers_from_tips_with_iwcs.csv"
CENTROID_SIMILARITIES_OF_ANSWERS_FROM_TIPS_WITH_IWCS_AND_BIDAF_FILE_PATH = "../data/Analysis_of_answers/centroid_similarities_of_answers_from_tips_with_iwcs_and_bidaf.csv"
CENTROID_SIMILARITIES_OF_ANSWERS_FROM_TIPS_WITH_IWCS_AND_BIDAF_WITH_LENGTH_BOUNDARY_FILE_PATH = "../data/Analysis_of_answers/centroid_similarities_of_answers_from_tips_with_iwcs_and_bidaf_with_length_boundary.csv"
CENTROID_SIMILARITIES_OF_ANSWERS_FROM_TIPS_WITH_TF_IDF_FILE_PATH = "../data/Analysis_of_answers/centroid_similarities_of_answers_from_tips_with_tf_idf.csv"
CENTROID_SIMILARITIES_OF_ANSWERS_FROM_TIPS_WITH_TF_IDF_AND_BIDAF_FILE_PATH = "../data/Analysis_of_answers/centroid_similarities_of_answers_from_tips_with_tf_idf_and_bidaf.csv"
CENTROID_SIMILARITIES_OF_ANSWERS_FROM_TIPS_WITH_TF_IDF_AND_BIDAF_WITH_LENGTH_BOUNDARY_FILE_PATH = "../data/Analysis_of_answers/centroid_similarities_of_answers_from_tips_with_tf_idf_and_bidaf_with_length_boundary.csv"

IWCS_SIMILARITIES_OF_ANSWERS_FROM_REVIEWS_WITH_TF_IDF_FILE_PATH = "../data/Analysis_of_answers/iwcs_similarities_of_answers_from_reviews_with_tf_idf.csv"
IWCS_SIMILARITIES_OF_ANSWERS_FROM_REVIEWS_WITH_TF_IDF_AND_BIDAF_FILE_PATH = "../data/Analysis_of_answers/iwcs_similarities_of_answers_from_reviews_with_tf_idf_and_bidaf.csv"
IWCS_SIMILARITIES_OF_ANSWERS_FROM_REVIEWS_WITH_TF_IDF_AND_BIDAF_WITH_LENGTH_BOUNDARY_FILE_PATH = "../data/Analysis_of_answers/iwcs_similarities_of_answers_from_reviews_with_tf_idf_and_bidaf_with_length_boundary.csv"
IWCS_SIMILARITIES_OF_ANSWERS_FROM_REVIEWS_WITH_CENTROID_FILE_PATH = "../data/Analysis_of_answers/iwcs_similarities_of_answers_from_reviews_with_centroid.csv"
IWCS_SIMILARITIES_OF_ANSWERS_FROM_REVIEWS_WITH_CENTROID_AND_BIDAF_FILE_PATH = "../data/Analysis_of_answers/iwcs_similarities_of_answers_from_reviews_with_centroid_and_bidaf.csv"
IWCS_SIMILARITIES_OF_ANSWERS_FROM_REVIEWS_WITH_CENTROID_AND_BIDAF_WITH_LENGTH_BOUNDARY_FILE_PATH = "../data/Analysis_of_answers/iwcs_similarities_of_answers_from_reviews_with_centroid_and_bidaf_with_length_boundary.csv"
IWCS_SIMILARITIES_OF_ANSWERS_FROM_TIPS_WITH_TF_IDF_FILE_PATH = "../data/Analysis_of_answers/iwcs_similarities_of_answers_from_tips_with_tf_idf.csv"
IWCS_SIMILARITIES_OF_ANSWERS_FROM_TIPS_WITH_TF_IDF_AND_BIDAF_FILE_PATH = "../data/Analysis_of_answers/iwcs_similarities_of_answers_from_tips_with_tf_idf_and_bidaf.csv"
IWCS_SIMILARITIES_OF_ANSWERS_FROM_TIPS_WITH_TF_IDF_AND_BIDAF_WITH_LENGTH_BOUNDARY_FILE_PATH = "../data/Analysis_of_answers/iwcs_similarities_of_answers_from_tips_with_tf_idf_and_bidaf_with_length_boundary.csv"
IWCS_SIMILARITIES_OF_ANSWERS_FROM_TIPS_WITH_CENTROID_FILE_PATH = "../data/Analysis_of_answers/iwcs_similarities_of_answers_from_tips_with_centroid.csv"
IWCS_SIMILARITIES_OF_ANSWERS_FROM_TIPS_WITH_CENTROID_AND_BIDAF_FILE_PATH = "../data/Analysis_of_answers/iwcs_similarities_of_answers_from_tips_with_centroid_and_bidaf.csv"
IWCS_SIMILARITIES_OF_ANSWERS_FROM_TIPS_WITH_CENTROID_AND_BIDAF_WITH_LENGTH_BOUNDARY_FILE_PATH = "../data/Analysis_of_answers/iwcs_similarities_of_answers_from_tips_with_centroid_and_bidaf_with_length_boundary.csv"

NUM_OF_ANSWERS_PER_QUESTION = 5
NUM_OF_FEATURES = 300
MAX_NUM_OF_FILTERS = 15
NUM_OF_FILTERS = 3
ANSWER_LENGTH_BOUNDARY = 24
NUMBER_OF_QUESTIONS_FOR_USER_TO_RATE = 64
NUMBER_OF_MODELS_FOR_USER_TO_RATE = 16

"""
YELP_MEAN_NUMBER_OF_WORDS_IN_REVIEWS = 14
YELP_MEAN_NUMBER_OF_WORDS_IN_TIPS = 12
YELP_STANDARD_DEVIATION_NUMBER_OF_WORDS_IN_REVIEWS = 10
YELP_STANDARD_DEVIATION_NUMBER_OF_WORDS_IN_TIPS = 11
YELP_MEAN_NUMBER_OF_WORDS_IN_REVIEWS_SPLIT_INTO_SENTENCES = 14
YELP_MEAN_NUMBER_OF_WORDS_IN_TIPS_SPLIT_INTO_SENTENCES = 7
YELP_STANDARD_DEVIATION_NUMBER_OF_WORDS_IN_REVIEWS_SPLIT_INTO_SENTENCES = 10
YELP_STANDARD_DEVIATION_NUMBER_OF_WORDS_IN_TIPS_SPLIT_INTO_SENTENCES = 5
"""
YELP_MEAN_NUMBER_OF_WORDS_FOR_TIPS_AND_REVIEWS = 23
YELP_STANDARD_DEVIATION_NUMBER_OF_WORDS_FOR_TIPS_AND_REVIEWS = 18
YELP_MEAN_NUMBER_OF_WORDS_FOR_TIPS_AND_REVIEWS_SPLIT_INTO_SENTENCES = 23
YELP_STANDARD_DEVIATION_NUMBER_OF_WORDS_FOR_TIPS_AND_REVIEWS_SPLIT_INTO_SENTENCES = 20

wv = None
index2word_set = None
tf_idf_from_tips = {}
tf_idf_from_reviews = {}

questions_from_yelp = []
questions_with_answers_list = []
predictor = None

bert_model = None
bert_tokenizer = None
